"""Generate reproducible source fixtures; run from any working directory."""

from pathlib import Path

ROOT = Path(__file__).parent / "fixtures"


def generate() -> None:
    ROOT.mkdir(exist_ok=True)
    samples = {
        "clean_ascii.txt": "A simple document.\nNo hidden content is intended.\n",
        "normal_utf8.txt": "Café, naïve, Ελληνικά, 日本語.\n",
        "isolated_zwsp.txt": "An isolated\u200b space.\n",
        "binary_zero_width.txt": "Visible text. " + "".join("\u200c" if bit == "1" else "\u200b"
            for byte in b"audit-id" for bit in f"{byte:08b}") + " End.\n",
        "bidi.txt": "Read \u202ereversed\u202c and \u2067isolated\u2069.\n",
        "variation_selectors.txt": "A" + "\ufe00\ufe01" * 8 + "\n",
        "normal_emoji.txt": "Family: 👩\u200d👩\u200d👧\u200d👦 Heart: ❤️ Flag: 🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f\n",
        "normal_persian.txt": "من می\u200cروم و می\u200cخوانم.\n",
        "normalization.txt": "Cafe\u0301 and fullwidth Ａ.\n",
        "tags.txt": "Visible" + "".join(chr(0xE0000 + ord(c)) for c in "provenance-id-12345678") + "\U000e007f\n",
        "periodic.txt": "abc\u200b" * 16,
        "source.html": "<!doctype html><html><!-- generated by: Example Tool --><p>text\u200b</p></html>\n",
        "source.json": '{"literal": "a\u200bb", "escaped": "\\u200b"}\n',
        "identifiers.md": "document-id: 12345678-1234-1234-1234-123456789abc\nRepeated: 12345678-1234-1234-1234-123456789abc\n",
        "mixed_endings.csv": "name,value\r\none,1\ntwo,2\r",
        "source.xml": '<?xml version="1.0"?><root>text\u2063</root>\n',
        "source.rst": "Title\n=====\nOrdinary text.\n",
        "mixed_script.txt": "pаypal\n",  # Cyrillic a.
    }
    for name, content in samples.items():
        (ROOT / name).write_bytes(content.encode("utf-8"))
    (ROOT / "bom.txt").write_bytes(b"\xef\xbb\xbfstart\xef\xbb\xbfend\n")
    (ROOT / "invalid_utf8.txt").write_bytes(b"valid prefix\xffsuffix")
    (ROOT / "control.txt").write_bytes(b"ordinary text with an unexpected \x00 byte\x1b and more prose\n")


if __name__ == "__main__":
    generate()
