"""Generate closed Office data records; semantic validators remain handwritten."""
import importlib.util
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location('office_schema', Path(__file__).with_name('build_schema.py'))
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
definitions = module.build()['$defs']
manual = {'officeSpan': 'Span', 'officeScalar': 'Scalar', 'officeSegment': 'Segment',
          'officeOrigin': 'Origin', 'officeControl': 'Control'}


def field(name):
    acronyms = {'id': 'ID', 'xml': 'XML', 'sha256': 'SHA256', 'utf8': 'UTF8', 'cdata': 'CDATA'}
    return ''.join(acronyms.get(word, word.title()) for word in name.split('_'))


def typename(name):
    if name == 'textHashes':
        return 'TextHashes'
    if name in manual:
        return manual[name]
    return name.removeprefix('office') if name.startswith('office') else field(name)


def go_type(schema):
    if '$ref' in schema:
        name = schema['$ref'].split('/')[-1]
        target = definitions[name]
        if target.get('type') == 'string':
            return 'string'
        return typename(name)
    if 'anyOf' in schema:
        assert len(schema['anyOf']) == 2 and schema['anyOf'][1] == {'type': 'null'}
        return '*' + go_type(schema['anyOf'][0])
    kind = schema.get('type')
    if kind == 'object':
        return 'struct {\n' + '\n'.join(
            f'{field(k)} {go_type(v)} `json:"{k}"`' for k, v in schema['properties'].items()) + '\n}'
    if kind == 'array':
        return '[]' + go_type(schema['items'])
    if kind == 'integer':
        return 'int64'
    if kind == 'boolean':
        return 'bool'
    if 'enum' in schema and all(type(v) is int for v in schema['enum']):
        return 'int64'
    if kind == 'string' or 'const' in schema or 'enum' in schema:
        return 'string'
    raise ValueError(schema)


def build():
    out = ['// Code generated by tests/contracts_v4/build_go_records.py; DO NOT EDIT.',
           'package v4', '']
    for name, schema in definitions.items():
        if (name.startswith('office') or name == 'textHashes') and name not in manual and schema.get('type') == 'object':
            out.append(f'type {typename(name)} {go_type(schema)}\n')
    return '\n'.join(out).encode()


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--gofmt', default='gofmt')
    args = parser.parse_args()
    result = subprocess.run([args.gofmt], input=build(), capture_output=True, check=True, timeout=15)
    (ROOT / 'internal/evidence/v4/records.go').write_bytes(result.stdout)
