// Code generated by tests/contracts_v4/build_go_records.py; DO NOT EDIT.
package v4

type TextHashes struct {
	RawTextSHA256           string `json:"raw_text_sha256"`
	NfcTextSHA256           string `json:"nfc_text_sha256"`
	NfkcTextSHA256          string `json:"nfkc_text_sha256"`
	FormattingRemovedSHA256 string `json:"formatting_removed_sha256"`
}

type Issue struct {
	Code          string  `json:"code"`
	DiagnosticRef *string `json:"diagnostic_ref"`
	PartRef       *string `json:"part_ref"`
}

type Outcome struct {
	Operation      string   `json:"operation"`
	PartRef        *string  `json:"part_ref"`
	State          string   `json:"state"`
	Codes          []string `json:"codes"`
	DiagnosticRefs []string `json:"diagnostic_refs"`
	Assessed       []Span   `json:"assessed"`
	Excluded       []Span   `json:"excluded"`
}

type Part struct {
	PartRef          string  `json:"part_ref"`
	PackageRef       string  `json:"package_ref"`
	Name             string  `json:"name"`
	ArtifactRef      string  `json:"artifact_ref"`
	Method           int64   `json:"method"`
	CompressedSpan   Span    `json:"compressed_span"`
	CompressedSHA256 string  `json:"compressed_sha256"`
	SHA256           *string `json:"sha256"`
	ByteLength       *int64  `json:"byte_length"`
	State            string  `json:"state"`
	Issues           []Issue `json:"issues"`
}

type Token struct {
	Index   int64  `json:"index"`
	Kind    string `json:"kind"`
	Span    Span   `json:"span"`
	Element *int64 `json:"element"`
}

type Element struct {
	Index     int64  `json:"index"`
	Parent    *int64 `json:"parent"`
	Namespace string `json:"namespace"`
	LocalName string `json:"local_name"`
	Span      Span   `json:"span"`
}

type XML struct {
	XMLRef        string    `json:"xml_ref"`
	PartRef       string    `json:"part_ref"`
	ParserVersion string    `json:"parser_version"`
	Tokens        []Token   `json:"tokens"`
	Elements      []Element `json:"elements"`
	Issues        []Issue   `json:"issues"`
	Segments      []Segment `json:"segments"`
	MapperVersion string    `json:"mapper_version"`
	Controls      []Control `json:"controls"`
}

type Boundary struct {
	XMLRef string `json:"xml_ref"`
	Token  int64  `json:"token"`
	Reason string `json:"reason"`
}

type Scope struct {
	ScopeRef         string     `json:"scope_ref"`
	PartRef          string     `json:"part_ref"`
	LocalID          string     `json:"local_id"`
	ExtractorVersion string     `json:"extractor_version"`
	AssemblerVersion string     `json:"assembler_version"`
	IdentitySHA256   string     `json:"identity_sha256"`
	Role             string     `json:"role"`
	Text             string     `json:"text"`
	SHA256           string     `json:"sha256"`
	Origins          []Origin   `json:"origins"`
	Hashes           TextHashes `json:"hashes"`
	Boundaries       []Boundary `json:"boundaries"`
	Issues           []Issue    `json:"issues"`
}

type StructuralLocation struct {
	Kind       string  `json:"kind"`
	PartRef    string  `json:"part_ref"`
	PartSHA256 string  `json:"part_sha256"`
	XMLRef     *string `json:"xml_ref"`
	Element    *int64  `json:"element"`
	Token      *int64  `json:"token"`
	Span       *Span   `json:"span"`
	ObjectRef  *string `json:"object_ref"`
}

type ScopeLocation struct {
	Kind     string `json:"kind"`
	ScopeRef string `json:"scope_ref"`
}

type OffsetLocation struct {
	Kind                  string  `json:"kind"`
	ScopeRef              string  `json:"scope_ref"`
	ScopeCharacterOffsets []int64 `json:"scope_character_offsets"`
	ScopeByteOffsets      []int64 `json:"scope_byte_offsets"`
}

type Metadata struct {
	Namespace        string   `json:"namespace"`
	LocalName        string   `json:"local_name"`
	LexicalValue     string   `json:"lexical_value"`
	NormalizedKey    *string  `json:"normalized_key"`
	PartRef          string   `json:"part_ref"`
	XMLRef           string   `json:"xml_ref"`
	Element          int64    `json:"element"`
	ValueOrigins     []Origin `json:"value_origins"`
	DuplicateOrdinal int64    `json:"duplicate_ordinal"`
}

type Relationship struct {
	RelationshipRef string             `json:"relationship_ref"`
	ID              string             `json:"id"`
	Type            string             `json:"type"`
	Target          string             `json:"target"`
	Mode            string             `json:"mode"`
	Location        StructuralLocation `json:"location"`
	SourceOwner     string             `json:"source_owner"`
	ResolutionState string             `json:"resolution_state"`
	ResolutionCode  *string            `json:"resolution_code"`
	TargetPartRef   *string            `json:"target_part_ref"`
}

type Object struct {
	ObjectRef         string   `json:"object_ref"`
	PartRef           string   `json:"part_ref"`
	SHA256            *string  `json:"sha256"`
	InclusionEvidence []string `json:"inclusion_evidence"`
	RelationshipRefs  []string `json:"relationship_refs"`
	DeclaredType      *string  `json:"declared_type"`
	ObservedSignature *string  `json:"observed_signature"`
	Inspection        Outcome  `json:"inspection"`
}

type Package struct {
	PackageRef        string    `json:"package_ref"`
	SourceSHA256      string    `json:"source_sha256"`
	SourceByteLength  int64     `json:"source_byte_length"`
	SourceArtifactRef string    `json:"source_artifact_ref"`
	ParserVersion     string    `json:"parser_version"`
	Format            string    `json:"format"`
	State             string    `json:"state"`
	Issues            []Issue   `json:"issues"`
	Parts             []Part    `json:"parts"`
	Outcomes          []Outcome `json:"outcomes"`
	Limits            struct {
		SourceBytes           int64 `json:"source_bytes"`
		PartCount             int64 `json:"part_count"`
		PartBytes             int64 `json:"part_bytes"`
		AggregateBytes        int64 `json:"aggregate_bytes"`
		MaxScopeTextUTF8Bytes int64 `json:"max_scope_text_utf8_bytes"`
		MaxScopeScalarOrigins int64 `json:"max_scope_scalar_origins"`
		ReportInputBytes      int64 `json:"report_input_bytes"`
		ReportOutputBytes     int64 `json:"report_output_bytes"`
		ReportNodes           int64 `json:"report_nodes"`
		ReportDepth           int64 `json:"report_depth"`
	} `json:"limits"`
}

type Evidence struct {
	Packages      []Package      `json:"packages"`
	XML           []XML          `json:"xml"`
	Scopes        []Scope        `json:"scopes"`
	Metadata      []Metadata     `json:"metadata"`
	Relationships []Relationship `json:"relationships"`
	Objects       []Object       `json:"objects"`
}
